version: '3.8'

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build: ./backend
    depends_on:
      postgresql-db:
        condition: service_healthy
    networks:
      - internal

  postgresql-db:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: leelibrary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/00-init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      postgresql-db:
        condition: service_healthy
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
